version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.5.3-stretch
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        PGUSER: root
    - image: circleci/postgres:9.6-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: sf_dahlia_test
  executor: ruby/default
aliases:
  - &attach_workspace
    attach_workspace:
      at: ~/repo
  - &restore_cache
    restore_cache:
        name: Restore Cache
        keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-{{ .Branch }}
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      # - *restore_cache
      - run:
          name: Install node
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v6.11.1' >> $BASH_ENV
            echo 'nvm alias default v6.11.1' >> $BASH_ENV
      - run: npm install
      - save_cache:
          name: Save Yarn Package Cache
          key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: Upgrade bundler
          command: |
            gem update --system
            gem install bundler
      - run: bundle install --deployment --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:test:prepare
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            ./tmp/cc-test-reporter before-build
      - run:
          name: Setup e2e
          command: |
            ./node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.41 --versions.standalone 3.141.59
            cat node_modules/protractor/node_modules/webdriver-manager/selenium/update-config.json
            sed -i 's/2\.45/2\.41/g' node_modules/protractor/node_modules/webdriver-manager/selenium/update-config.json
            cat node_modules/protractor/node_modules/webdriver-manager/selenium/update-config.json
            ./node_modules/protractor/bin/webdriver-manager status
      - persist_to_workspace:
          root: .
          paths:
            - .
  backend:
    <<: *defaults
    steps:
      - checkout
      - *attach_workspace
      - *restore_cache
      - run:
          name: Upgrade bundler
          command: |
            gem update --system
            gem install bundler
      - run: bundle --path vendor/bundle
      - run: bundle exec rake jasmine:ci
      - run: bundle exec rake spec
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - backend:
          requires:
            - build