---
http_interactions:
- request:
    method: post
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/oauth2/token"
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.15.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 07 Jul 2020 18:07:17 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D1F000000I2yHm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00D1F000000I2yHm"
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=saqmK8B8EeqGDt3m_C4m2Q; domain=.salesforce.com; path=/; expires=Wed,
        07-Jul-2021 18:07:17 GMT; Max-Age=31536000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://test.salesforce.com/id/00D1F000000I2yHUAS/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1594145237896","signature":"xROlO8tzisHQbu5LapFZuoDjANy7Vc8Z7hXDq3elpO8="}'
    http_version: 
  recorded_at: Tue, 07 Jul 2020 18:07:17 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm/a0o0P00000FEUwC"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.15.4
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 07 Jul 2020 18:07:18 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D1F000000I2yHm";
      Expect-Ct:
      - max-age=86400, report-uri="https://a.forcesslreports.com/Expect-CT-report/00D1F000000I2yHm"
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=se_tPcB8EeqvR11ZVGDHGg; domain=.salesforce.com; path=/; expires=Wed,
        07-Jul-2021 18:07:18 GMT; Max-Age=31536000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[{"zip":null,"state":null,"shortformPreferenceID":"a0w0P00000MPK72QAH","requiresProof":false,"recordTypeDevName":"COP","preferenceProof":null,"postLotteryValidation":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvAQAX","individualPreference":null,"city":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o0P00000FEUwCQAX","address":null},{"zip":null,"state":null,"shortformPreferenceID":"a0w0P00000MPK9yQAH","requiresProof":false,"recordTypeDevName":"L_W","preferenceProof":null,"postLotteryValidation":"Unconfirmed","optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvFQAX","individualPreference":"Work
        in SF","city":null,"certificateNumber":null,"appMemberID":"a0n0P00000AwpIPQAZ","applicationID":"a0o0P00000FEUwCQAX","address":null}],"referral":"Email
        Alert","primaryApplicant":{"zip":"52694-8379","yCoordinate":null,"xCoordinate":null,"workInSf":"true","whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":"Ne","sexualOrientationOther":null,"sexualOrientation":"Straight/Heterosexual","sexAtBirth":null,"relationship":null,"raceEthnicity":null,"race":null,"primaryLanguage":null,"preferenceAddressMatch":null,"phoneType":"Cell","phone":"1-467-830-2589x9722","pacificIslanderOther":null,"otherLanguage":null,"noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":"95993-4315","mailingState":"No","mailingCity":"North
        Teresa","mailingAddress":"77009 Garcia Grove Suite 199","lendingAgentStatus":null,"latinoOther":null,"lastName":"Smith","indigenousOther":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"David","ethnicity":"Hispanic/Latino","email":"andreawallace@example.com","DOB":"1976-10-05","DALPCertified":null,"contactId":"0030P000020bdvhQAA","city":"SAN
        LEANDRO","candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpIPQAZ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"78482
        Janet Burgs","accountId":null,"acceptingNewMOHCDClients":null},"otherHousingCounselingAgency":null,"name":"APP-00038757","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038757","listingID":"a0W0P00000DZTkAUAX","lendingAgent":null,"isFirstTimeHomebuyer":false,"id":"a0o0P00000FEUwCQAX","housingCounselingAgency":null,"householdVouchersSubsidies":"false","householdMembers":[],"homebuyerEducationAgency":null,"hasSenior":null,"hasPublicHousing":null,"hasMilitaryService":null,"hasLoanPreapproval":false,"hasDevelopmentalDisability":null,"hasCompletedHomebuyerEducation":false,"formMetadata":"{\"completedSections\":{\"Intro\":true,\"You\":true,\"Household\":true,\"Preferences\":true,\"Income\":true}}","externalSessionId":"","didApplicantUseHousingCounselingAgency":"No","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2017-03-02","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":75000.00,"alternateContact":null,"agreeToTerms":true,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Tue, 07 Jul 2020 18:07:18 GMT
recorded_with: VCR 5.0.0
