---
http_interactions:
- request:
    method: post
    uri: https://test.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 27 Feb 2018 22:51:43 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Content-Security-Policy:
      - upgrade-insecure-requests
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=9SCWw92RQxyPStrspsnpSA;Path=/;Domain=.salesforce.com;Expires=Sat,
        28-Apr-2018 22:51:43 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://sfhousing--full.cs96.my.salesforce.com","id":"https://test.salesforce.com/id/00D1g0000004c5rEAA/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1519771904199","signature":"QNZrRKwtdfPNxtP+giaZBLtmuAE1SRZJbXU8AtsYvRM="}'
    http_version: 
  recorded_at: Tue, 27 Feb 2018 22:51:44 GMT
- request:
    method: get
    uri: https://sfhousing--full.cs96.my.salesforce.com/services/apexrest/shortForm/a0o0P00000FEUwH
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.9.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 27 Feb 2018 22:51:44 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://calm-dawn-26291.herokuapp.com/hpkp-report/00D1g0000004c5rp";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=AY9Qb9Z8RTCdAzW6nubPKw;Path=/;Domain=.salesforce.com;Expires=Sat,
        28-Apr-2018 22:51:44 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[{"shortformPreferenceID":"a0w0P00000MPK73QAH","requiresProof":false,"recordTypeDevName":"COP","preferenceProof":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvAQAX","individualPreference":null,"certificateNumber":null,"appMemberID":null,"applicationID":"a0o0P00000FEUwHQAX"},{"shortformPreferenceID":"a0w0P00000MPK9zQAH","requiresProof":false,"recordTypeDevName":"L_W","preferenceProof":null,"optOut":false,"naturalKey":null,"lwPreferenceProof":null,"listingPreferenceID":"a0l0P00001JEWvFQAX","individualPreference":"Live
        in SF","certificateNumber":null,"appMemberID":"a0n0P00000AwpInQAJ","applicationID":"a0o0P00000FEUwHQAX"}],"referral":"MOHCD
        Website","primaryApplicant":{"zip":"94114-3022","yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":"CA","sexualOrientationOther":null,"sexualOrientation":"Straight/Heterosexual","sexAtBirth":null,"relationship":null,"race":"White","preferenceAddressMatch":null,"phoneType":"Cell","phone":"4153707354","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":"94114-3022","mailingState":"CA","mailingCity":"SAN
        FRANCISCO","mailingAddress":"221 LIBERTY ST","lastName":"Michaelson","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":"Male","firstName":"Marc","ethnicity":"Not
        Hispanic/Latino","email":"marcmichaelson@me.com","DOB":"1950-02-22","contactId":"0030P000020bdxYQAQ","city":"SAN
        FRANCISCO","candidateScore":null,"appMemberType":"Primary Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":"Work","alternatePhone":"4154203846","alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":"221
        LIBERTY ST"},"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0W0P00000DZTkAUAX","id":"a0o0P00000FEUwHQAX","householdVouchersSubsidies":"false","householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Ferraro","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":"true","hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Rachele","ethnicity":null,"email":null,"DOB":"1955-06-05","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n0P00000AwpIkQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null},{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":"true","whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Child","race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lastName":"Ferraro-Michaelson","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":"true","hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Gabriella","ethnicity":null,"email":null,"DOB":"2000-10-10","contactId":null,"city":null,"candidateScore":null,"appMemberType":"Household
        Member","appMemberId":"a0n0P00000AwpIlQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null}],"hasPublicHousing":null,"hasMilitaryService":null,"hasDevelopmentalDisability":null,"formMetadata":"{\"completedSections\":{\"Intro\":true,\"You\":true,\"Household\":true,\"Preferences\":true,\"Income\":true}}","externalSessionId":"","appRTType":"Rental_Short_Form","applicationSubmittedDate":"2017-03-02","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":95000.00,"alternateContact":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"race":null,"preferenceAddressMatch":null,"phoneType":null,"phone":"4154203846","noPhone":false,"noEmail":false,"noAddress":false,"middleName":null,"mailingZip":"94114","mailingState":"CA","mailingCity":"San
        Francisco","mailingAddress":"221 Liberty St","lastName":"Ferraro","languageOther":null,"language":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Rachele","ethnicity":null,"email":"holisticdc@me.com","DOB":null,"contactId":null,"city":null,"candidateScore":null,"appMemberType":"Alternate
        Contact","appMemberId":"a0n0P00000AwpImQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":"Family
        Member","agency":null,"address":null},"agreeToTerms":true,"adaPrioritiesSelected":null}'
    http_version: 
  recorded_at: Tue, 27 Feb 2018 22:51:44 GMT
recorded_with: VCR 3.0.3
